# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Awesome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Awesome

  target 'Awesome-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Awesome-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Awesome-tvOS

end
