# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TrackierSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackierSDK
  pod 'trackier-ios-sdk', '1.6.29'
  pod 'React'
end